import type { NextPage } from 'next';
import * as gtag from '@/lib/gtag';
import { useRef } from 'react';
import Head from 'next/head';

const Login: NextPage = () => {
  const value = useRef<number>(0);
  const onClickLogin = () => {
    gtag.event({
      action: '로그인을 했습니다.',
      category: '로그인',
      label: '로그인',
      value,
    });
    value.current = value.current + 1;
    console.log(value.current);
  };
  return (
    <>
      {' '}
      <Head>
        <title>로그인</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>로그인</div>
      <button onClick={onClickLogin}>로그인 버튼 !!!!</button>
    </>
  );
};

export default Login;
